import { Camera } from '@/components/Core/Camera'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen flex flex-col lg:flex-row">
          <div className="w-full lg:w-[50vw]">{children}</div>
          <div className="w-full h-full flex items-center justify-center bg-primary-700">
            <Camera />
          </div>
        </div>
      </body>
    </html>
  )
}
